---
title: "Ozflux Benchmarks"
output:
    # pdf_document:
    #     toc: true
    html_document:
        toc: true
        theme: united
        css: ozflux-benchmarks.css
        self_contained: true
classoption: 
  landscape
---

```{r setup, include=FALSE}
# knitr options
# knitr::opts_chunk$set(echo = FALSE,
#                       message = FALSE,
#                       out.width = "100%",
#                       fig.height = 7,
#                       warning = debug)

# kable options
# opts <- options(knitr.kable.NA = "")

library("tidyr")
library("htmltools")
library("htmlwidgets")
library("DGVMTools")
library("daveanalysis")
library("plotly")
dave_config(log_level = 4, log_file = "ozflux-benchmarks.log")
```

```{r echo = FALSE, message = FALSE, warning = FALSE, results = "asis", fig.asp = 0.7, fig.width = 11}
cat("\n\nGenerated", format(Sys.time(), "%a %b %e %Y"), "\n\n")

# Can specify paths to multiple repositories like this:
# sources <- c("/path/to/guess/repo/0", "/path/to/guess/repo/1")
# Or by calling defineSource(), which gives more control over the name:
source_descriptions <- c()
sources <- c()
define_source <- function(name, path, description) {
    if (!dir.exists(path)) {
        stop("Directory not found: '", path, "'")
    }
    source_descriptions <<- c(source_descriptions, description)
    sources <<- c(sources, defineSource(
        id = basename(path),
        name = name,
        dir = path,
        format = OZFLUX))
}
define_source("DAVE", "/home/drew/code/lpj-guess/dave", "Latest Dave branch with all dave switches enabled except for hydraulics. Max 1 tree cohort per PFT. rootdist water uptake method. Measured fluxes used for climate data. Run on lpjguess_dave branch (4feb77a133eff573ff233fbd96bf1ebd357454e2)")
define_source("DAVE_BARRA2", "/home/drew/code/lpj-guess/dave3", "Latest Dave branch with all dave switches enabled except for hydraulics. Max 1 tree cohort per PFT. rootdist water uptake method. BARRA2 used for climate data. Run on lpjguess_dave branch (4feb77a133eff573ff233fbd96bf1ebd357454e2)")
define_source("Trunk", "/home/drew/code/lpj-guess/trunk", "Trunk with global pfts and rootdist water uptake method, run on the lpjguess_dave_baseline branch (2ec439fbd48a9bf326d5a2d76eb35bff706f0bd9)")

# define_source("DAVE", "/home/drew/code/lpj-guess/dave", "Dave branch with dave photosynthesis and trunk allocation, after fixing leap years bug, with all pfts except shrubs running in competition. Unlimited number of tree cohorts. rootdist water uptake method. Run on lpjguess_dave branch (448d767c197ee264d7a029ca3aea82e09f57b426)")
# define_source("Trunk", "/home/drew/code/lpj-guess/dave3", "Dave branch with all dave switches disabled, with global pfts and rootdist water uptake method, run on the lpjguess_dave_baseline branch after fixing leap years bug (c42f294e94968b351cf0b8f6507321c5d784448d)")

sites <- NULL # Plot all sites
# sites <- c("CumberlandPlain") # Plot a subset of sites

vars <- NULL # Plot all standard variables
# vars <- c("dave_gpp") # Plot of a subset of variables

# Set to true to use plotly for graph rendering. Note: requires rendering to
# HTML; see document header. Note also that embedding lots of plotlies in a
# single document is not conducive to a good benchmarking experience (as the
# document is slow to load and sluggish once loaded).
plotly <- FALSE
if (is.null(sites) || is.null(vars) || length(sites) > 1 || length(vars) > 1) {
    plotly <- FALSE
}

ozflux_benchmarks(sources, source_descriptions, use_plotly = plotly,
                  sites = sites, vars = vars)
```
