
#' @format An S4 class object with the slots as defined below.
#' @rdname Layer-class
#' @keywords datasets
ozflux_layers <- list(
  # BOREAL TREES
  new("Layer",
      id = "BNE",
      name = "Boreal Needleleaved Evergreen Tree",
      colour = "darkblue",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Needleleaved",
                        phenology = "Evergreen",
                        climate.zone = "Boreal",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "BINE",
      name = "Boreal Shade-Intolerant Needleleaved Evergreen Tree",
      colour = "dodgerblue3",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Needleleaved",
                        phenology = "Evergreen",
                        climate.zone = "Boreal",
                        shade.tolerance = "BNE",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "BNS",
      name = "Boreal Needleleaved Summergreen Tree",
      colour = "cadetblue2",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Needleleaved",
                        phenology = "Summergreen",
                        climate.zone = "Boreal",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "IBS",
      name = "Shade-intolerant B/leaved Summergreen Tree",
      colour = "chartreuse",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Summergreen",
                        climate.zone = "Temperate",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  
  # TEMPERATE TREES
  new("Layer",
      id = "TeBE",
      name = "Temperate Broadleaved Evergreen Tree",
      colour = "darkgreen",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Evergreen",
                        climate.zone = "Temperate",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "TeNE",
      name = "Temperate Needleleaved Evergreen Tree",
      colour = "lightseagreen",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Needleleaved",
                        phenology = "Evergreen",
                        climate.zone = "Temperate",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "TeBS",
      name = "Temperate Broadleaved Summergreen Tree",
      colour = "darkolivegreen3",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Summergreen",
                        climate.zone = "Temperate",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  
  
  # TROPICAL TREES
  new("Layer",
      id = "TrBE",
      name = "Tropical Broadleaved Evergreen Tree",
      colour = "orchid4",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Evergreen",
                        climate.zone = "Tropical",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "TrIBE",
      name = "Tropical Shade-intolerant Broadleaved Evergreen Tree",
      colour = "orchid",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Evergreen",
                        climate.zone = "Tropical", 
                        shade.tolerance = "TrBE",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "TrBR",
      name = "Tropical Broadleaved Raingreen Tree",
      colour = "palevioletred",
      properties = list(type = "PFT",
                        growth.form = "Tree",
                        leaf.form = "Broadleaved",
                        phenology = "Raingreen",
                        climate.zone = "Tropical",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  
  
  # GRASSES
  new("Layer",
      id = "C3G",
      name = "Boreal/Temperate Grass",
      colour = "lightgoldenrod1",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "C3G_annual",
      name = "Annual C3 Grass",
      colour = "lightgoldenrod1",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "C3G_perennial",
      name = "Perennial C3 Grass",
      colour = "lightgoldenrod1",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "C4G",
      name = "Tropical Grass",
      colour = "sienna1",
      properties = list(type = "PFT",
                        name = "Tropical Grass",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ), 
  new("Layer",
      id = "C4G_annual",
      name = "Annual C4 Grass",
      colour = "sienna1",
      properties = list(type = "PFT",
                        name = "Tropical Grass",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "C4G_perennial",
      name = "Perennial C4 Grass",
      colour = "sienna1",
      properties = list(type = "PFT",
                        name = "Tropical Grass",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  # SHRUBS
  new("Layer",
      id = "BLSE",
      name = "Boreal Evergreen Low Shrub",
      colour = "plum",
      properties = list(type = "PFT",
                        name = "Boreal Evergreen Low Shrub",
                        growth.form = "Shrub",
                        leaf.form = "Needleleaved",
                        phenology = "Evergreen",
                        climate.zone = "Boreal",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "BLSS",
      name = "Boreal Summergreen Low Shrub",
      colour = "mistyrose3",
      properties = list(type = "PFT",
                        name = "Boreal Summergreen Low Shrub",
                        growth.form = "Shrub",
                        leaf.form = "Broadleaved",
                        phenology = "Summergreen",
                        climate.zone = "Boreal",
                        shade.tolerance = "None",
                        land.cover = "Natural")
  ),
  
  # PASTURE PFTS
  new("Layer",
      id = "C3G_pas",
      name = "Boreal/Temperate Pasture Grass",
      colour = "lightgoldenrod4",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Pasture")
  ),
  new("Layer",
      id = "C4G_pas",
      name = "Tropical Pasture Grass",
      colour = "sienna3",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Pasture")
  ),
  
  # CROP AND INTERCROP GRASS PFTS
  new("Layer",
      id = "CC3G_ic",
      name = "Boreal/Temperate Intercrop Grass",
      colour = "palegreen2",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland")
  ),
  new("Layer",
      id = "CC4G_ic",
      name = "Tropical Intercrop Grass",
      colour = "palegreen4",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "GrassPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland")
  ),
  new("Layer",
      id = "CC3ann",
      name = "C3 Annual Crop",
      colour = "red",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = FALSE)
  ),
  new("Layer",
      id = "CC3per",
      name = "C3 Perennial Crop",
      colour = "red",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = FALSE)
  ),
  new("Layer",
      id = "CC3nfx",
      name = "C3 Nitrogen Fixing Crop",
      colour = "red",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = FALSE)
  ),
  new("Layer",
      id = "CC4ann",
      name = "C4 Annual Crop",
      colour = "red",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = FALSE)
  ),
  new("Layer",
      id = "CC4per",
      name = "C4 Perennial Crop",
      colour = "red",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = FALSE)
  ),
  new("Layer",
      id = "CC3anni",
      name = "Irrigated C3 Annual Crop",
      colour = "slategray",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = TRUE)
  ),
  new("Layer",
      id = "CC3peri",
      name = "Irrigated C3 Perennial Crop",
      colour = "slategray",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = TRUE)
  ),
  new("Layer",
      id = "CC3nfxi",
      name = "Irrigated C3 Nitrogen Fixing Crop",
      colour = "slategray",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = TRUE)
  ),
  new("Layer",
      id = "CC4anni",
      name = "Irrigiated C4 Annual Crop",
      colour = "slategray",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = TRUE)
  ),
  new("Layer",
      id = "CC4peri",
      name = "Irrigated C4 Perennial Crop",
      colour = "slategray",
      properties = list(type = "PFT",
                        growth.form = "Grass",
                        leaf.form = "Broadleaved",
                        phenology = "CropPhenology",
                        climate.zone = "NA",
                        shade.tolerance = "None",
                        land.cover = "Cropland",
                        irrigated = TRUE)
  ),
  
  # PFT LANDCOVER AGGREGATES
  new("Layer",
      id = "Crop_sum",
      name = "Crop Sum",
      colour = "Red",
      properties = list(type = "Sum",
                        land.cover = "Cropland")
  ),
  new("Layer",
      id = "Pasture_sum",
      name = "Pasture Sum",
      colour = "springgreen3",
      properties = list(type = "Sum",
                        land.cover = "Pasture")
  ),
  new("Layer",
      id = "Natural_sum",
      name = "Natural Sum",
      colour = "saddlebrown",
      properties = list(type = "Sum",
                        land.cover = "Natural")
  ),
  new("Layer",
      id = "Barren_sum",
      name = "Barren Sum",
      colour = "gray75",
      properties = list(type = "Sum",
                        land.cover = "Barren")
  ),
  new("Layer",
     id = "Total",
     name = "Total",
     colour = "black",
     properties = list(type = "Sum",
                       land.cover = "All")
  )
  
  
)

#####################################################################
########### LPJ-GUESS(-SPITFIRE) QUANTITIES ########################
#####################################################################

#' @format The \code{\linkS4class{Quantity}} class is an S4 class with the slots defined below
#' @rdname Quantity-class
#' @keywords datasets
#' 
#' 
ozflux_quantities <- list(
  new("Quantity",
      id = "lai",
      name = "LAI",
      units = "m^2/m^2",
      colours = function(n) rev(viridis::viridis(n)),
      format = c("GUESS"),
      standard_name = "leaf_area_index"),
  
  new("Quantity",
      id = "mlai",
      name = "Monthly LAI",
      units = "m^2/m^2",
      colours = viridis::viridis,
      format = c("GUESS"),
      standard_name = "leaf_area_index"),
  
  new("Quantity",
      id = "fpc",
      name = "Foliar Projective Cover",
      units = "m^2/m^2",
      colours = grDevices::colorRampPalette(c("white", "darkolivegreen1", "darkolivegreen4", "saddlebrown", "black")),
      format = c("GUESS")),
  
  new("Quantity",
      id = "mfpc",
      name = "Monthly Foliar Projective Cover",
      units = "m^2/m^2",
      colours = grDevices::colorRampPalette(c("white", "darkolivegreen1", "darkolivegreen4", "saddlebrown", "black")),
      format = c("GUESS")),
  
  new("Quantity",
      id = "vegcover",
      name = "Vegetation Cover",
      units = "%",
      colours = grDevices::colorRampPalette(c("white", "darkolivegreen1", "darkolivegreen4", "saddlebrown", "black")),
      format = c("GUESS")),
  
  new("Quantity",
      id = "agpp",
      name = "Annual GPP",
      units = "kgC/m2/year",
      colours = viridis::inferno,
      format = c("GUESS")),
  
  new("Quantity",
      id = "cmass",
      name = "Vegetation Carbon Mass",
      units = "kgC/m^2",
      colours = viridis::viridis,
      format = c("GUESS")),
  
  new("Quantity",
      id = "clitter",
      name = "Litter Carbon Mass",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "agb",
      name = "Above Ground Biomass",
      units = "tonnes/hectare",
      colours = viridis::viridis,
      format = c("GUESS")),
  
  new("Quantity",
      id = "cpool",
      name = "Carbon Pools",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "litter_wood",
      name = "Wood Litter",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "litter_leaf",
      name = "Leaf Litter",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "litter_repr",
      name = "Reproductive Litter",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "fine_fuel",
      name = "Fine Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mnpp",
      name = "NPP",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mgpp",
      name = "GPP",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mnee",
      name = "Monthly NEE",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mrh",
      name = "Monthly Heterotrophic Respiration",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mra",
      name = "Monthly Autotrophic Respiration",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "anpp",
      name = "Annual NPP",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "cflux",
      name = "Carbon Flux",
      units = "kgC/m^2/y",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "dens",
      name = "PFT Density",
      units = "indiv/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "speciesheights",
      name = "PFT Average Heights",
      units = "m",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "height",
      name = "PFT Average Heights",
      units = "m",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "canopyheight",
      name = "Canopy Height",
      units = "m",
      colours = function(n) rev(viridis::magma(n)),
      format = c("GUESS"),
      standard_name = "canopy_height"),
  
  new("Quantity",
      id = "doc",
      name = "Dissolved Organic Carbon (?)",
      units = "kgC/m^2/year",
      colours = function(n) rev(viridis::magma(n)),
      format = c("GUESS"),
      standard_name = "canopy_height"),
  
  new("Quantity",
      id = "maet",
      name = "Monthly Actual Evapotranspiration",
      units = "mm/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mpet",
      name = "Monthly Potential Evapotranspiration",
      units = "mm/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mevap",
      name = "Monthly Evaporation",
      units = "mm/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mrunoff",
      name = "Monthly Runoff",
      units = "mm/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mintercep",
      name = "Monthly Interception",
      units = "mm/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mwcont_upper",
      name = "Monthly Upper Soil Layer",
      units = "fraction",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("GUESS")),
  
  new("Quantity",
      id = "mwcont_lower",
      name = "Monthly Lower Soil Layer",
      units = "fraction",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("GUESS")),
  
  new("Quantity",
      id = "msnowpack",
      name = "Monthly Snow Pack",
      units = "mm H20",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("GUESS")),
  
  new("Quantity",
      id = "aaet",
      name = "Annual Actual Evapotranspiration",
      units = "mm/year",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "aiso",
      name = "Annual Isoprene Emissions",
      units = "kg/year",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  
  new("Quantity",
      id = "miso",
      name = "Monthly Isoprene Emissions",
      units = "kg/month",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "amon",
      name = "Annual Monoterpene Emissions",
      units = "kg/year",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mmon",
      name = "Monthly Monoterpene Emissions",
      units = "kg/year",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "firert",
      name = "Fire Return Interval",
      units = "years",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("GUESS")),
  
  new("Quantity",
      id = "monthly_burned_area",
      name = "Monthly Burned Area Fraction",
      units = "fraction",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mburned_area",
      name = "Monthly Burned Area Fraction",
      units = "fraction",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "annual_burned_area",
      name = "Annual Burned Area Fraction",
      units = "fraction",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "aburned_area",
      name = "Annual Burned Area Fraction",
      units = "fraction",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fireseason",
      name = "Fire Season Length",
      units = "days",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "firesl",
      name = "Fire Season Length",
      units = "days",
      colours =viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "burntarea", 
      name = "Annual Fraction Burned",
      units = "fraction of gridcell",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "burntfraction",
      name = "Annual Fraction Burned",
      units = "fraction of gridcell",
      colours = viridis::turbo,
      format = c("GUESS"),
      standard_name = "burned_area_fraction"),
  
  new("Quantity",
      id = "tot_runoff",
      name = "Runoff",
      units = "mm/year",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "vmaxnlim",
      name = "Nitrogen Limitation to Vmax",
      units = "fraction",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "bioclim",
      name = "Bioclimatic Limit Variables",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "gdd5",
      name = "Growing Degree Days (5deg C base)",
      units = "degree days",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  
  new("Quantity",
      id = "aleafshed",
      name = "Number times leafs shed per year",
      units = "",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "cton_leaf",
      name = "C:N leaf",
      units = "ckgC/kgN",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "nmass",
      name = "Vegetation Nitrogen Mass",
      units = "kgN/m^2",
      colours = viridis::viridis,
      format = c("GUESS")),
  
  new("Quantity",
      id = "ngases",
      name = "Annual Nitrogren Gases Emissions",
      units = "kg/ha/year",
      colours = viridis::viridis,
      format = c("GUESS")),
  
  new("Quantity",
      id = "npool",
      name = "Nitrogen",
      units = "kgN/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "nuptake",
      name = "Nitrogen Uptake",
      units = "kgN/ha",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "nsources",
      name = "Nitrogen Source",
      units = "gN/ha",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  
  new("Quantity",
      id = "nflux",
      name = "Nitrogen Flux",
      units = "kgN/ha",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "nlitter",
      name = "Litter Nitrogen Mass",
      units = "kgN/ha",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mprec",
      name = "Monthly Precipitation",
      units = "mm",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mtemp",
      name = "Mean Monthly Temperature",
      units = "deg C",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mwmass_stem",
      name = "Water Stored in Stem",
      units = "kgH20/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "mwmass_leaf",
      name = "Water Stored in Leaves",
      units = "kgH20/m^2",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  new("Quantity",
      id = "bioclim_mtemps",
      name = "Bioclimactic Temperatures",
      units = "deg C",
      colours = viridis::turbo,
      format = c("GUESS")),
  new("Quantity",
      id = "dave_soil_psi",
      name = "Soil Water Potential",
      units = "MPa",
      colours = viridis::turbo,
      format = c("GUESS")),
  
  
  #############################################################################################
  ############################# LPJ-GUESS-SPITFIRE QUANTITIES #################################
  #############################################################################################
  
  new("Quantity",
      id = "mfirefrac",
      name = "Monthly Burned Area Fraction",
      units = "",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mtau_l",
      name = "Monthly Residence Time",
      units = "mins",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "pyro_flux",
      name = "Pyrogenic Emmisions",
      units = "kg species/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireintens",
      name = "Monthly Fire Intensity",
      units = "kW/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_fuel",
      name = "Mean Monthly Live Grass Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_fuel",
      name = "Mean Monthly 1hr Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_fuel",
      name = "Mean Monthly 10hr Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m100hr_fuel",
      name = "Mean Monthly 100hr Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_fuel",
      name = "Mean Monthly 1000hr Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_cc",
      name = "Mean Monthly Live Grass Combustion Completeness",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_cc",
      name = "Mean Monthly 1hr Combustion Completeness",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_cc",
      name = "Mean Monthly 10hr Combustion Completeness",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id ="m100hr_cc",
      name = "Mean Monthly 100hr Combustion Completeness",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_cc",
      name = "Mean Monthly 1000hr Combustion Completeness",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "afdays",
      name = "Fire Days per Year",
      units = "days",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mavenest",
      name = "Average Monthly Nesterov",
      units = "",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_livegrass",
      name = "Monthly Litter Moisture of Live Grass",
      units = "",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_deadfuel",
      name = "Monthly Litter Moisture of Dead Fuel",
      units = "",
      colours = function(n) rev(viridis::turbo(n)),
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "meff_wind",
      name = "Monthly Effective Windspeed",
      units = "m/min",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnfdi",
      name = "Monthly Nesterov Fire Danger Index",
      units = "m/min",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "mFBD",
      name = "Monthly Fuel Bulk Density",
      units = "m^3/m^3",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mSAV",
      name = "Monthly Surface Area to Volume Ratio",
      units = "m^2/m^3",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mMoE",
      name = "Monthly Moisture of Extinction",
      units = "",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mmcont",
      name = "Monthly Fuel Moisture Content",
      units = "",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_durat",
      name = "Monthly Fire Duration",
      units = "mins",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mscorch_height",
      name = "Monthly Scorch Height",
      units = "m",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mRoS",
      name = "Monthly Rate of Spread",
      units = "m/min",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_size",
      name = "Monthly Fire Size",
      units = "ha",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "real_fire_size",
      name = "Fire Size",
      units = "ha",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mhuman_ign",
      name = "Monthly average of human ignition rate",
      units = "ign/day",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlightning_ign",
      name = "Monthly average of lightning ignition rate",
      units = "ign/day",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_duration",
      name = "Monthly Fire Duration (Fire Days Only)",
      units = "mins",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_scorch_height",
      name = "Monthly Scorch Height (Fire Days Only)",
      units = "m",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_intensity",
      name = "Monthly Fire Intensity (Fire Days Only)",
      units = "kW/m",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_nesterov",
      name = "Monthly Nesterov (Fire Days Only)",
      units = "",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_residence_time",
      name = "Monthly Residence Time (Fire Days Only)",
      units = "min",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "allocation_fails",
      name = "Monthly Allocation Fails",
      units = "days",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "allocation_iters",
      name = "Monthly Iteration To Allocation Fire",
      units = "days",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfuel",
      name = "Monthly Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfinefuel",
      name = "Monthly Fine Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mleaffuel",
      name = "Monthly Leaf Fuel",
      units = "kgC/m^2",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfiredays",
      name = "Monthly sum of daily fire probabilites",
      units = "days",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfiredaysfine",
      name = "Monthly sum of daily fire probabilites (based on fine fuel threshold)",
      units = "days",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  
  # Daily fire properties
  new("Quantity",
      id = "daily_fires_diagnostics",
      name = "Daily fire properties",
      units = "mixed",
      colours = viridis::turbo,
      format = c("LPJ-GUESS-SPITFIRE")),
  new("Quantity",
      id = "dave_resp_leaf",
      name = "Daily Leaf Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_root",
      name = "Daily Root Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_sap",
      name = "Daily Sapwood Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_crown",
      name = "Daily Crown Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_repr",
      name = "Daily Reproductive Tissue Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_growth",
      name = "Daily Growth Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS")),
  new("Quantity",
      id = "dave_resp_maintenance",
      name = "Daily Maintenance Respiration",
      units = "gC/m2",
      colours = viridis::turbo,
      format = c("OZFLUX", "GUESS"))
  
  
)
